# Generated by Django 2.0.2 on 2018-11-09 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, null=True)),
                ('escuela', models.CharField(max_length=65, null=True)),
                ('semestre', models.IntegerField(null=True)),
                ('egresado', models.BooleanField(default=False)),
                ('carrera', models.CharField(max_length=65, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='seleccionar cuando el alumno sea verificado con sus documentos.deseleccionar si el alumno no esta comprobado como un estudiante')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_alumno', 'Is_Alumno'),),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridad', models.CharField(default='sin definir', max_length=75)),
                ('experiencia', models.TextField(default='sin experiencia previa')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
