# Generated by Django 2.0.2 on 2018-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(default=False, help_text='seleccionar cuando el alumno sea verificado con sus documentos.deseleccionar si el alumno no esta comprobado como un estudiante'),
        ),
    ]
