# Generated by Django 2.0.2 on 2018-09-22 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('representante', models.CharField(max_length=105)),
                ('is_active', models.BooleanField(default=False, help_text='seleccionar cuando la empresa sea verificado con sus documentos.deseleccionar si la empresa no esta comprobado')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_empresa', 'Is_Empresa'),),
            },
        ),
    ]
