# Generated by Django 2.0.2 on 2018-11-09 01:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, unique=True)),
                ('RFC', models.CharField(max_length=50, unique=True)),
                ('sector', models.CharField(max_length=75, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='seleccionar cuando la empresa sea verificado con sus documentos.deseleccionar si la empresa no esta comprobado')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_empresa', 'Is_Empresa'),),
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('descripcion', models.TextField(default='contactanos para mas detalles.')),
                ('escolaridad', models.CharField(max_length=65)),
                ('carrera', models.CharField(max_length=65)),
                ('egresado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertaEmpresa', to='empresa.Empresa')),
            ],
        ),
    ]
