# Generated by Django 2.0.2 on 2018-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto_empresa',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='foto',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
