# Generated by Django 2.0.2 on 2018-09-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
